baseURL = "https://examplesite.com/"
disqusShortname = ""
languageCode = "en-us"
paginate = "8"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Satyanchal's Blog"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "tools"
name = "tools"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2021 [Satyanchal](https://satyanchal-blog.netlify.app/) All Rights Reserved"
description = "This is meta description"
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm Satyanchal. <br> I help people make their software best"
[params.cookies]
enable = true
expire_days = 2
[params.cta]
description = "I'm a 🎓Student, 💻 Developer and 🎨 Artist!"
enable = true
image = "https://avatars.githubusercontent.com/u/62104921?s=460&u=6d82589db09324b10017ae3ba4418e613c807c69&v=4"
title = "Hey! I am Satyanchal"
[params.cta.button]
enable = true
label = "Contact me"
link = "https://satyanchal-blog.netlify.app/contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
